#!/bin/bash

clear

[[ "$(whoami)" != "root" ]] && {

echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"

rm $HOME/Plus > /dev/null 2>&1; exit 0

}

_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')

cd $HOME

fun_bar () {

comando[0]="$1"

comando[1]="$2"

(

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} -y > /dev/null 2>&1

${comando[1]} -y > /dev/null 2>&1

touch $HOME/fim

) > /dev/null 2>&1 &

tput civis

echo -ne "  \033[1;33mติดตั้งแพ็คเกจ \033[1;37m- \033[1;33m["

while true; do

for((i=0; i<18; i++)); do

echo -ne "\033[1;31m#"

sleep 0.1s

done

[[ -e $HOME/fim ]] && rm $HOME/fim && break

echo -e "\033[1;33m]"

sleep 1s

tput cuu1

tput dl1

echo -ne "  \033[1;33mติดตั้งแพ็คเกจ \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

function verif_key () {

krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1

[[ ! -e "$_Ink/list" ]] && {

echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"

rm -rf $HOME/Plus > /dev/null 2>&1

sleep 2

clear; exit 1

}

}

      echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

       tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "  ZOOM PLUS PERSONAL " ; tput sgr0

      echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

echo ""

echo -e "             \033[1;31mสนใจ! \033[1;33mสำหรับการติดตั้ง สคริปต์ !\033[0m"

echo ""

echo -e "\033[1;31m• \033[1;33mติดตั้งชุดสคริปต์เป็นเครื่องมือ\033[0m"

echo -e "\033[1;33m  สำหรับการจัดการระบบเครือข่าย  และผู้ใช้ \033[0m"

echo ""

echo -e "\033[1;32m• \033[1;36mคำเตือน! \033[1;33mการติดตั้งสคริปต์เกิน1ครั้งอาจทำให้เครื่อง VPS เสียหาย!\033[0m"

echo -e "\033[1;33m  แพ็คเกจบางอย่างจำเป็นอย่างยิ่ง กรุณาอย่าปิดหน้าจอ!\033[0m"

echo ""

echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mแก้ไขโดย:ZOOM-VPN\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"

echo ""

#-----------------------------------------------------------------------------------------------------------------

echo -ne "\033[1;36m GERAR KEY FREE [N/Y]: \033[1;37m"; read x

[[ $x = @(n|N) ]] && exit

sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1

service ssh restart  > /dev/null 2>&1

echo -e "\n\033[1;36mตรวจสอบ... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink http://103.169.67.47:81/SAMUPlus/Install/list > /dev/null 2>&1; verif_key

sleep 1s

echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1

rm versao* > /dev/null 2>&1

wget https://raw.githubusercontent.com/leitura/SSHPLUS/master/Install/versao > /dev/null 2>&1

> /dev/null 2>&1

wget https://www.xvideos.com > /dev/null 2>&1

> /dev/null 2>&1

rm TheMentalistSay > /dev/null 2>&1

cd /bin/ > /dev/null 2>&1

rm v2raymanager > /dev/null 2>&1

wget https://raw.githubusercontent.com/leitura/SSHPLUS/master/Modulos/v2raymanager > /dev/null 2>&1

#-----------------------------------------------------------------------------------------------------------------

echo -e "\n\033[1;32mตรวจสอบผ่าน!\033[1;32m"

sleep 1s

echo ""

[[ -f "$HOME/usuarios.db" ]] && {

clear

echo ""

echo -e "\n\033[0;31m═════════════════════════════════════════════════\033[0m"

echo -e "                 \033[1;33m• \033[1;31mตรวจพบฐานข้อมูลเดิม \033[1;33m• \033[0m"

echo ""

echo -e "Encontrada! Deseja mantê-la preservando o limite"

echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"

echo -e "criar uma nova base de dados ?\033[0m"

echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mติดตั้งใหม่โดยใช้ฐานข้อมูลใหม่\033[0m"

echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mติดตั้งใหม่โดยใช้ฐานข้อมูลเดิม\033[0m"

echo -e "\n\033[0;31m═════════════════════════════════════════════════\033[0m"

echo ""

tput setaf 2 ; tput bold ; read -p "เลือก?: " -e -i 1 optiondb ; tput sgr0

} || {

awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db

}

[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db

clear

      echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

       tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " ZOOM PLUS PERSONAL" ; tput sgr0

      echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

echo ""

echo ""

echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้งแพ็คเกจขั้น1 \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"

echo ""

echo -e "    \033[1;33mการติดตั้งจะใช้เวลาสักครู่!\033[0m"

echo ""

fun_attlist () {

apt-get update -y

[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus

echo "crz: $(date)" > /usr/share/.plus/.plus

}

fun_bar 'fun_attlist'

clear

echo ""

echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้งแพ็คเกจขั้นที่2 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"

echo ""

echo -e "\033[1;33m แพ็คเกจบางอย่างจำเป็นอย่างยิ่ง กรุณาอย่าปิดหน้าจอ!\033[0m"

echo ""

inst_pct () {

_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")

for _prog in ${_pacotes[@]}; do

apt install $_prog -y

done

pip install speedtest-cli

}

fun_bar 'inst_pct'

[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp

clear

echo ""

echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้งแพ็คเกจขั้นที่3 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"

echo ""

echo -e "      \033[1;33m แพ็คเกจบางอย่างจำเป็นอย่างยิ่ง กรุณาอย่าปิดหน้าจอ! \033[0m"

echo ""

fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"

clear

echo ""

cd $HOME

echo -e "  ZOOM-PLUS" | figlet

 echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

echo -e "       \033[1;33m≠×≠×≠×≠×\033[1;36m ยินดีด้วยการติดตั้งเสร็จสมบูรณ์แล้ว \033[1;33m≠×≠×≠×≠×\033[0m"

 echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

echo ""

echo -e "\033[1;31m \033[1;33mใส่คำสั่งหลัก: \033[1;32mmenu\033[0m"

echo -e "\033[1;33mติดต่อสอบถามเพิ่มเติม \033[1;31m(\033[1;36mติดต่อ \033[1;31m): \033[1;37mfacebook:คนไทยนี้ดี เป็นพี่ เป็นน้อง\033[0m"

rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
